title: SF Tabs
description: Custom Tabs for Salesforce Setup
baseurl: "/sftabs"
url: "https://chrisrouse.github.io"

# Theme settings
theme: just-the-docs
color_scheme: light

# Logo and branding
logo: "/assets/images/icon128.png"

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation settings
nav_sort: order

# Footer content
footer_content: "&copy; 2025 SF Tabs by Chris Rouse. Based on the original work of Warren Walter and the <a href=\"https://github.com/walters954/why-salesforce\">Why Salesforce</a> plugin."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GitHub link
gh_edit_link: false
gh_edit_repository: "https://github.com/chrisrouse/sftabs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Aux links for the navigation
aux_links:
  "SF Tabs on GitHub":
    - "https://github.com/chrisrouse/sftabs"

# Makes aux links open in new tab
aux_links_new_tab: true

# Heading anchor links
heading_anchors: true

# Enable copy button on code blocks
enable_copy_code_button: true

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
